apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: library-front
  template:
    metadata:
      labels:
        app: library-front
    spec:
      containers:
      - name: library-front
        image: vkdahdk/library-front:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: production
        # Add any other environment variables needed for your Next.js app