apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: MSA-BestBook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vkdahdk/infra.git
    path: applications/MSA-BestBook
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true