apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: MSA-Book
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pang2moa/library-infra.git
    path: applications/MSA-Book
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true